/** Seed venues for Hitchhiker's Guide to Finsbury Park (London). */
export type PlaceType =
  | "anchor"
  | "park"
  | "transit"
  | "culture"
  | "food"
  | "sport"
  | "hq"
  | "trail"
  | "music"
  | string

export type Place = {
  id: string
  name: string
  shortName: string
  type: PlaceType
  coords: [number, number] // [lng, lat]
  subtitle?: string
  region?: string
  sector?: string
  desc?: string
  trailFile?: string
  starQuestId?: string
    googleMaps?: string
  link?: string
  siteLabel?: string
  [key: string]: unknown
}

/** Unity WorldMomentSites.FinsburyLat/Lon */
export const FINSBURY: [number, number] = [-0.0998, 51.5714]

export const PLACES: Place[] = [
  {
    id: "finsbury-park",
    name: "Finsbury Park",
    shortName: "FINSBURY PARK",
    type: "park",
    coords: [-0.0998, 51.5714],
    subtitle: "Haringey / Islington · London Field Guide anchor",
    region: "North London",
    sector: "Endymion Road · Seven Sisters Road",
    desc: "46-hectare Victorian park and the Field Guide daily London stand-in (Unity City Dressing + Avebury world-moment testing). Green lung between Manor House and Finsbury Park stations.",
    googleMaps: "https://maps.google.com/?q=Finsbury+Park+London",
    link: "https://haringey.gov.uk/leisure-parks-culture/parks-greenspaces/parks-facilities-haringey/finsbury-park",
    siteLabel: "Official site",
  },
  {
    id: "manor-house",
    name: "Manor House Station",
    shortName: "Manor House",
    type: "transit",
    coords: [-0.0962, 51.5708],
    subtitle: "Piccadilly line · park east gate",
    region: "North London",
    sector: "Green Lanes",
    desc: "Primary tube arrival for park walks. Natural Beam-In for Field Guide London sessions.",
    googleMaps: "https://maps.google.com/?q=Manor+House+Underground+Station",
    link: "https://tfl.gov.uk/tube/stop/940GZZLUMRH/manor-house-underground-station",
    siteLabel: "TfL",
  },
  {
    id: "finsbury-park-station",
    name: "Finsbury Park Station",
    shortName: "FP Station",
    type: "transit",
    coords: [-0.1065, 51.5645],
    subtitle: "National Rail · Victoria · Piccadilly",
    region: "North London",
    sector: "Station Place",
    desc: "Major interchange on the west-south edge of the park. Good alternate start for northbound trails.",
    googleMaps: "https://maps.google.com/?q=Finsbury+Park+Station",
    link: "https://tfl.gov.uk/tube/stop/940GZZLUFPK/finsbury-park-underground-station",
    siteLabel: "TfL",
  },
  {
    id: "hitchhiker-house",
    name: "Hitchhiker House",
    shortName: "HITCHHIKER HOUSE",
    type: "hq",
    coords: [-0.10505, 51.56332],
    subtitle: "33 Vaudeville Court · N4 2QG",
    region: "Islington",
    sector: "St Thomas's Road · Finsbury Park",
    desc: "Hitchhikers house at 33 Vaudeville Court, St Thomas's Road, Finsbury Park. Field Guide London HQ: Beam-In, bag drop, and the walk's start.",
    googleMaps: "https://maps.google.com/?q=33+Vaudeville+Court+St+Thomas's+Road+London+N4+2QG",
  },
  {
    id: "arsenal-emirates",
    name: "Emirates Stadium",
    shortName: "Emirates",
    type: "sport",
    coords: [-0.1084, 51.5549],
    subtitle: "Arsenal FC · ~1.2 km south",
    region: "Holloway",
    sector: "Hornsey Road",
    desc: "Neighbourhood landmark south of the park. Match-day crowds reshape the Field Guide street layer.",
    googleMaps: "https://maps.google.com/?q=Emirates+Stadium",
    link: "https://www.arsenal.com/emirates-stadium",
    siteLabel: "Venue site",
  },
  {
    id: "jab-sw1-victoria",
    name: "JAB Boxing Club SW1",
    shortName: "JAB Victoria",
    type: "sport",
    coords: [-0.14726, 51.49274],
    subtitle: "Open · boutique performance club",
    region: "Victoria",
    sector: "Unit 5, Colonnade Walk · 151 Buckingham Palace Road · SW1W 9SZ",
    desc: "JAB SW1 is the open Victoria club: 6,500 sq ft of high-performance boxing, training studios, and a recovery suite under mid-century interiors. Victoria / National Rail hop from Finsbury Park Station.",
    link: "https://jabboxing.club/clubs/sw1-victoria/",
    googleMaps: "https://maps.google.com/?q=151+Buckingham+Palace+Road+London+SW1W+9SZ",
  },
  {
    id: "jab-ec1-moorgate",
    name: "JAB Boxing Club EC1",
    shortName: "JAB East",
    type: "sport",
    coords: [-0.09015, 51.52281],
    subtitle: "Opening Autumn 2026 · Hylo, Bunhill Row",
    region: "Moorgate / EC1",
    sector: "Unit 3, Hylo · 105 Bunhill Row · EC1Y 8LZ",
    desc: "East London flagship opening Autumn 2026. Three floors at Hylo: open gym, boxing and train studios, recovery, Joey's restaurant, and lounge. Founding membership is live now. Moorgate / Old Street / Liverpool Street. Same Finsbury / Bunhill fringe as the Field Guide Ink trail.",
    link: "https://jabboxing.club/clubs/ec1-moorgate/",
    googleMaps: "https://maps.google.com/?q=105+Bunhill+Row+London+EC1Y+8LZ",
  },
  {
    id: "trail-jab-sw1-gloves",
    name: "JAB SW1 Street Gloves",
    shortName: "Street gloves",
    type: "trail",
    coords: [-0.14726, 51.49274],
    subtitle: "Collect six gloves · NFT into your wallet",
    region: "Victoria",
    sector: "Around JAB SW1",
    trailFile: "jab-sw1-gloves.geojson",
    starQuestId: "8f2c1a4e-6b7d-4c91-a3e5-1d9f0b4e7c22",
    desc: "Street hunt around JAB Boxing Club SW1. Each glove is a STAR objective. Check-in mints an SPL NFT to the avatar Solana wallet, then records progress. Pin id, objective title, and NFT trailPinId are the same string.",
    googleMaps: "https://maps.google.com/?q=151+Buckingham+Palace+Road+London+SW1W+9SZ",
    link: "https://jabboxing.club/clubs/sw1-victoria/",
    siteLabel: "JAB SW1",
  },
  {
    id: "parkland-walk-gate",
    name: "Parkland Walk approach",
    shortName: "Parkland Walk",
    type: "park",
    coords: [-0.1035, 51.5682],
    subtitle: "Former railway trail · nature corridor",
    region: "Haringey",
    sector: "Upper Holloway / Stroud Green",
    desc: "Linear nature reserve linking toward Highgate. Companion green route for longer Field Guide walks.",
    googleMaps: "https://maps.google.com/?q=Parkland+Walk+Finsbury+Park",
    link: "https://www.parkland-walk.org.uk/",
    siteLabel: "Official site",
  },
  {
    id: "crouch-end",
    name: "Crouch End Broadway",
    shortName: "Crouch End",
    type: "culture",
    coords: [-0.1235, 51.5792],
    subtitle: "TrustGraph / Spaces neighbour · west of park",
    region: "Haringey",
    sector: "The Broadway",
    desc: "Independent high street used in TrustGraph London demos. Natural hop from Finsbury for witness / POI work.",
    googleMaps: "https://maps.google.com/?q=Crouch+End+Broadway",
    link: "https://en.wikipedia.org/wiki/Crouch_End",
    siteLabel: "Area guide",
  },
  {
    id: "newspeak-house",
    name: "Newspeak House",
    shortName: "Newspeak House",
    type: "culture",
    coords: [-0.07124, 51.52529],
    subtitle: "London College of Political Technology",
    region: "Shoreditch",
    sector: "133-135 Bethnal Green Road · E2 7DG",
    desc: "Independent residential college and civic-tech campus at Brick Lane and Bethnal Green Road. Public events, fellowship, and community nights; nearest Overground is Shoreditch High Street. Visit by event or appointment.",
    link: "https://newspeak.house/",
    googleMaps: "https://maps.google.com/?q=Newspeak+House+133-135+Bethnal+Green+Road+London+E2+7DG",
    siteLabel: "College site",
  },
  {
    id: "new-river-cafe-edge",
    name: "New River path (park edge)",
    shortName: "New River",
    type: "park",
    coords: [-0.0948, 51.5735],
    subtitle: "Historic watercourse · east fringe",
    region: "Haringey",
    sector: "Green Lanes corridor",
    desc: "Quiet water edge east of the park for narration stops and optional drop placement.",
    googleMaps: "https://maps.google.com/?q=New+River+Path+Finsbury+Park",
    link: "https://en.wikipedia.org/wiki/New_River_(London)",
    siteLabel: "Official site",
  },
  {
    id: "music-park-theatre",
    name: "Park Theatre",
    shortName: "Park Theatre",
    type: "music",
    coords: [-0.10848, 51.56573],
    subtitle: "Clifton Terrace · 2 min from FP station",
    region: "Finsbury Park",
    sector: "Clifton Terrace · N4 3JP",
    desc: "Neighbourhood theatre with music nights, comedy, and talks. Closest stage door to Hitchhiker House.",
    link: "https://parktheatre.co.uk/",
    googleMaps: "https://maps.google.com/?q=Park+Theatre+Finsbury+Park",
  },
  {
    id: "music-worlds-end",
    name: "The World's End",
    shortName: "World's End",
    type: "music",
    coords: [-0.10833, 51.56699],
    subtitle: "Live music weekends · Stroud Green Road",
    region: "Finsbury Park",
    sector: "21–23 Stroud Green Road · N4 3EF",
    desc: "Pub stage two minutes from the station: weekend live music, rockeoke, comedy, and match-day noise.",
    link: "https://www.worldsendfinsburypark.com/",
    googleMaps: "https://maps.google.com/?q=The+Worlds+End+Finsbury+Park",
  },
  {
    id: "music-twelve-pins",
    name: "The Twelve Pins",
    shortName: "Twelve Pins",
    type: "music",
    coords: [-0.10479, 51.56482],
    subtitle: "Irish pub · Station Place",
    region: "Finsbury Park",
    sector: "Station Place",
    desc: "Station-side Irish pub with regular sessions and gig nights. Natural post-Beam-In pint stop.",
    link: "https://www.twelvepinspub.co.uk/",
    googleMaps: "https://maps.google.com/?q=The+Twelve+Pins+Finsbury+Park",
  },
  {
    id: "music-faltering-fullback",
    name: "The Faltering Fullback",
    shortName: "Fullback",
    type: "music",
    coords: [-0.1082, 51.56852],
    subtitle: "Perth Road · garden + sessions",
    region: "Finsbury Park",
    sector: "Perth Road",
    desc: "Local favourite north of the station. Garden nights and occasional live sets between the sport screens.",
    link: "https://falteringfullback.com/",
    googleMaps: "https://maps.google.com/?q=The+Faltering+Fullback+Finsbury+Park",
  },
  {
    id: "music-the-finsbury",
    name: "The Finsbury",
    shortName: "The Finsbury",
    type: "music",
    coords: [-0.09631, 51.57195],
    subtitle: "Green Lanes · intimate gigs",
    region: "Haringey",
    sector: "Green Lanes · N4",
    desc: "Compact gig room on Green Lanes, east of the park. Good for small bills and local bands.",
    link: "https://www.thefinsbury.co.uk/",
    googleMaps: "https://maps.google.com/?q=The+Finsbury+Green+Lanes+London",
  },
  {
    id: "music-garage",
    name: "The Garage",
    shortName: "The Garage",
    type: "music",
    coords: [-0.10396, 51.54675],
    subtitle: "Highbury · indie / rock landmark",
    region: "Highbury",
    sector: "Highbury Corner",
    desc: "North London rite-of-passage venue. Short hop south on Victoria / Piccadilly from Finsbury Park.",
    link: "https://www.thegarage.london/",
    googleMaps: "https://maps.google.com/?q=The+Garage+Highbury+London",
  },
  {
    id: "music-nambucca",
    name: "Nambucca",
    shortName: "Nambucca",
    type: "music",
    coords: [-0.12366, 51.56105],
    subtitle: "Holloway Road · ~300 capacity",
    region: "Holloway",
    sector: "596 Holloway Road · N7 6LB",
    desc: "Relaxed live room on Holloway Road. Regular gig nights between Archway and Finsbury Park.",
    link: "https://www.skiddle.com/whats-on/London/Nambucca/",
    googleMaps: "https://maps.google.com/?q=Nambucca+Holloway+Road+London",
  },
  {
    id: "music-union-chapel",
    name: "Union Chapel",
    shortName: "Union Chapel",
    type: "music",
    coords: [-0.10244, 51.54482],
    subtitle: "Islington · church acoustic landmark",
    region: "Islington",
    sector: "Compton Terrace",
    desc: "Grade I chapel gigs: folk, jazz, and sitting-down legends. South of the park via Highbury.",
    link: "https://www.unionchapel.org.uk/",
    googleMaps: "https://maps.google.com/?q=Union+Chapel+Islington",
  },
  {
    id: "music-assembly-hall",
    name: "Islington Assembly Hall",
    shortName: "Assembly Hall",
    type: "music",
    coords: [-0.10244, 51.54155],
    subtitle: "Upper Street · mid-size hall",
    region: "Islington",
    sector: "Upper Street",
    desc: "Art-deco mid-size hall for touring acts. Easy Victoria-line hop from Finsbury Park.",
    link: "https://www.islingtonassemblyhall.co.uk/",
    googleMaps: "https://maps.google.com/?q=Islington+Assembly+Hall",
  },
  {
    id: "music-o2-academy",
    name: "O2 Academy Islington",
    shortName: "O2 Academy",
    type: "music",
    coords: [-0.1057, 51.53457],
    subtitle: "N1 Centre · big room",
    region: "Islington",
    sector: "N1 Centre",
    desc: "Larger Islington room for bigger bills and club nights.",
    link: "https://www.academymusicgroup.com/o2academyislington/",
    googleMaps: "https://maps.google.com/?q=O2+Academy+Islington",
  },
  {
    id: "music-boston",
    name: "Boston Music Room",
    shortName: "Boston Music Room",
    type: "music",
    coords: [-0.13838, 51.55733],
    subtitle: "Tufnell Park · upstairs / The Dome",
    region: "Tufnell Park",
    sector: "Dartmouth Park Hill",
    desc: "Twin-room complex (Boston Music Room + The Dome) west of the park. Steady indie and metal calendar.",
    link: "https://www.bostonmusicroom.co.uk/",
    googleMaps: "https://maps.google.com/?q=Boston+Music+Room+London",
  },
  {
    id: "music-forum",
    name: "O2 Forum Kentish Town",
    shortName: "O2 Forum",
    type: "music",
    coords: [-0.1422, 51.55214],
    subtitle: "Kentish Town · theatre-scale gigs",
    region: "Kentish Town",
    sector: "Highgate Road",
    desc: "Former cinema, now a major north-London gig hall west of Finsbury Park.",
    link: "https://www.academymusicgroup.com/o2forumkentishtown/",
    googleMaps: "https://maps.google.com/?q=O2+Forum+Kentish+Town",
  },
  {
    id: "music-ally-pally",
    name: "Alexandra Palace",
    shortName: "Ally Pally",
    type: "music",
    coords: [-0.13064, 51.59435],
    subtitle: "Ally Pally · hilltop arena",
    region: "Muswell Hill",
    sector: "Alexandra Palace Way",
    desc: "North London's hilltop palace for festivals, arena gigs, and fireworks. Long walk or bus from the park.",
    link: "https://www.alexandrapalace.com/",
    googleMaps: "https://maps.google.com/?q=Alexandra+Palace+London",
  },
  {
    id: "music-salisbury",
    name: "The Salisbury",
    shortName: "The Salisbury",
    type: "music",
    coords: [-0.09938, 51.58223],
    subtitle: "Green Lanes · grand Victorian pub",
    region: "Harringay",
    sector: "Green Lanes",
    desc: "Ornate Victorian pub north-east of the park. Occasional live nights and a Field Guide-worthy interior.",
    link: "https://thesalisburyhotelpub.co.uk/",
    googleMaps: "https://maps.google.com/?q=The+Salisbury+Green+Lanes+London",
  },
  {
    id: "trail-killer",
    name: "Killer In The Code",
    shortName: "Killer / Code",
    type: "trail",
    coords: [-0.0965, 51.5215],
    subtitle: "Desk stand-in trail · Field Guide pack",
    region: "London desk geometry",
    sector: "StreamingAssets stand-in",
    trailFile: "killer-in-the-code.geojson",
    starQuestId: "00df145e-461b-434f-9372-d10c84f2b6df",
    desc: "Phygital cipher trail (Zodiac / Dahlia geography) authored for Field Guide. Geometry currently desk-stand-in near central London; load pins on the map from the trail file.",
    googleMaps: "https://maps.google.com/?q=51.5215,-0.0965",
  },
  {
    id: "trail-highgate",
    name: "Highgate East Ideas",
    shortName: "Highgate East",
    type: "trail",
    coords: [-0.0975, 51.5217],
    subtitle: "Desk stand-in · memorial tone",
    trailFile: "grave-highgate-east.geojson",
    starQuestId: "1d1fb9ec-3868-454d-9076-6a79c5cec924",
    desc: "Ideas walk pack (Karl Marx stand-in geometry in current StreamingAssets). Select to plot trail pins.",
    googleMaps: "https://maps.google.com/?q=Highgate+Cemetery+East",
    link: "https://highgatecemetery.org/",
    siteLabel: "Official site",
  },
  {
    id: "trail-bunhill",
    name: "Bunhill Ink",
    shortName: "Bunhill Ink",
    type: "trail",
    coords: [-0.0961, 51.5223],
    subtitle: "Desk stand-in · Blake / dissenting voices",
    trailFile: "grave-bunhill-ink.geojson",
    starQuestId: "27f5cfa1-31ad-4b14-abb0-8ada21f60672",
    desc: "Literary / dissenting London pack. Load GeoJSON pins from StreamingAssets mirror.",
    googleMaps: "https://maps.google.com/?q=Bunhill+Fields+Burial+Ground",
    link: "https://www.cityoflondon.gov.uk/services/parks/bunhill-fields-burial-ground",
    siteLabel: "Official site",
  },
  {
    id: "trail-bow-street",
    name: "Bow Street Law Walk",
    shortName: "Bow Street",
    type: "trail",
    coords: [-0.0972, 51.52085],
    subtitle: "Desk stand-in · magistrates & pubs",
    trailFile: "pub-bow-street-law.geojson",
    starQuestId: "ca62cdd7-358f-405b-aa22-d14ffb532f32",
    desc: "Law-and-tavern walk pack for Field Guide London demos.",
    googleMaps: "https://maps.google.com/?q=Bow+Street+London",
    link: "https://www.bowstreet.co.uk/",
    siteLabel: "Official site",
  },
  {
    id: "london-hub",
    name: "London (Field Guide)",
    shortName: "LONDON",
    type: "anchor",
    coords: [-0.0998, 51.5714],
    subtitle: "OASIS · Hitchhikers Guide city entry",
    region: "United Kingdom",
    sector: "Finsbury Park anchor",
    desc: "City-scale Hitchhikers Guide entry. Finsbury Park is the default feet-on-ground lens for London Field Guide iteration.",
    googleMaps: "https://maps.google.com/?q=Finsbury+Park+London",
  },
]
